'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.0.3705.288
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.0.3705.288.
'
Namespace com.amazon.soap
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="AmazonSearchBinding", [Namespace]:="urn:PI/DevCentral/SoapService"),  _
     System.Xml.Serialization.SoapIncludeAttribute(GetType(ItemQuantity)),  _
     System.Xml.Serialization.SoapIncludeAttribute(GetType(AddItem)),  _
     System.Xml.Serialization.SoapIncludeAttribute(GetType(Item)),  _
     System.Xml.Serialization.SoapIncludeAttribute(GetType(SellerSearchDetails)),  _
     System.Xml.Serialization.SoapIncludeAttribute(GetType(Feedback)),  _
     System.Xml.Serialization.SoapIncludeAttribute(GetType(SellerProfileDetails)),  _
     System.Xml.Serialization.SoapIncludeAttribute(GetType(CustomerReview)),  _
     System.Xml.Serialization.SoapIncludeAttribute(GetType(Track)),  _
     System.Xml.Serialization.SoapIncludeAttribute(GetType(BrowseNode)),  _
     System.Xml.Serialization.SoapIncludeAttribute(GetType(ThirdPartyProductDetails)),  _
     System.Xml.Serialization.SoapIncludeAttribute(GetType(KeyPhrase)),  _
     System.Xml.Serialization.SoapIncludeAttribute(GetType(Details))>  _
    Public Class AmazonSearchService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://soap.amazon.com/onca/soap2"
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:PI/DevCentral/SoapService", RequestNamespace:="urn:PI/DevCentral/SoapService", ResponseNamespace:="urn:PI/DevCentral/SoapService")>  _
        Public Function KeywordSearchRequest(<System.Xml.Serialization.SoapElementAttribute("KeywordSearchRequest")> ByVal KeywordSearchRequest1 As KeywordRequest) As <System.Xml.Serialization.SoapElementAttribute("return")> ProductInfo
            Dim results() As Object = Me.Invoke("KeywordSearchRequest", New Object() {KeywordSearchRequest1})
            Return CType(results(0),ProductInfo)
        End Function
        
        '<remarks/>
        Public Function BeginKeywordSearchRequest(ByVal KeywordSearchRequest1 As KeywordRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("KeywordSearchRequest", New Object() {KeywordSearchRequest1}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndKeywordSearchRequest(ByVal asyncResult As System.IAsyncResult) As ProductInfo
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),ProductInfo)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:PI/DevCentral/SoapService", RequestNamespace:="urn:PI/DevCentral/SoapService", ResponseNamespace:="urn:PI/DevCentral/SoapService")>  _
        Public Function PowerSearchRequest(<System.Xml.Serialization.SoapElementAttribute("PowerSearchRequest")> ByVal PowerSearchRequest1 As PowerRequest) As <System.Xml.Serialization.SoapElementAttribute("return")> ProductInfo
            Dim results() As Object = Me.Invoke("PowerSearchRequest", New Object() {PowerSearchRequest1})
            Return CType(results(0),ProductInfo)
        End Function
        
        '<remarks/>
        Public Function BeginPowerSearchRequest(ByVal PowerSearchRequest1 As PowerRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("PowerSearchRequest", New Object() {PowerSearchRequest1}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndPowerSearchRequest(ByVal asyncResult As System.IAsyncResult) As ProductInfo
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),ProductInfo)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:PI/DevCentral/SoapService", RequestNamespace:="urn:PI/DevCentral/SoapService", ResponseNamespace:="urn:PI/DevCentral/SoapService")>  _
        Public Function BrowseNodeSearchRequest(<System.Xml.Serialization.SoapElementAttribute("BrowseNodeSearchRequest")> ByVal BrowseNodeSearchRequest1 As BrowseNodeRequest) As <System.Xml.Serialization.SoapElementAttribute("return")> ProductInfo
            Dim results() As Object = Me.Invoke("BrowseNodeSearchRequest", New Object() {BrowseNodeSearchRequest1})
            Return CType(results(0),ProductInfo)
        End Function
        
        '<remarks/>
        Public Function BeginBrowseNodeSearchRequest(ByVal BrowseNodeSearchRequest1 As BrowseNodeRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("BrowseNodeSearchRequest", New Object() {BrowseNodeSearchRequest1}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndBrowseNodeSearchRequest(ByVal asyncResult As System.IAsyncResult) As ProductInfo
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),ProductInfo)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:PI/DevCentral/SoapService", RequestNamespace:="urn:PI/DevCentral/SoapService", ResponseNamespace:="urn:PI/DevCentral/SoapService")>  _
        Public Function AsinSearchRequest(<System.Xml.Serialization.SoapElementAttribute("AsinSearchRequest")> ByVal AsinSearchRequest1 As AsinRequest) As <System.Xml.Serialization.SoapElementAttribute("return")> ProductInfo
            Dim results() As Object = Me.Invoke("AsinSearchRequest", New Object() {AsinSearchRequest1})
            Return CType(results(0),ProductInfo)
        End Function
        
        '<remarks/>
        Public Function BeginAsinSearchRequest(ByVal AsinSearchRequest1 As AsinRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("AsinSearchRequest", New Object() {AsinSearchRequest1}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndAsinSearchRequest(ByVal asyncResult As System.IAsyncResult) As ProductInfo
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),ProductInfo)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:PI/DevCentral/SoapService", RequestNamespace:="urn:PI/DevCentral/SoapService", ResponseNamespace:="urn:PI/DevCentral/SoapService")>  _
        Public Function UpcSearchRequest(<System.Xml.Serialization.SoapElementAttribute("UpcSearchRequest")> ByVal UpcSearchRequest1 As UpcRequest) As <System.Xml.Serialization.SoapElementAttribute("return")> ProductInfo
            Dim results() As Object = Me.Invoke("UpcSearchRequest", New Object() {UpcSearchRequest1})
            Return CType(results(0),ProductInfo)
        End Function
        
        '<remarks/>
        Public Function BeginUpcSearchRequest(ByVal UpcSearchRequest1 As UpcRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("UpcSearchRequest", New Object() {UpcSearchRequest1}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndUpcSearchRequest(ByVal asyncResult As System.IAsyncResult) As ProductInfo
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),ProductInfo)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:PI/DevCentral/SoapService", RequestNamespace:="urn:PI/DevCentral/SoapService", ResponseNamespace:="urn:PI/DevCentral/SoapService")>  _
        Public Function AuthorSearchRequest(<System.Xml.Serialization.SoapElementAttribute("AuthorSearchRequest")> ByVal AuthorSearchRequest1 As AuthorRequest) As <System.Xml.Serialization.SoapElementAttribute("return")> ProductInfo
            Dim results() As Object = Me.Invoke("AuthorSearchRequest", New Object() {AuthorSearchRequest1})
            Return CType(results(0),ProductInfo)
        End Function
        
        '<remarks/>
        Public Function BeginAuthorSearchRequest(ByVal AuthorSearchRequest1 As AuthorRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("AuthorSearchRequest", New Object() {AuthorSearchRequest1}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndAuthorSearchRequest(ByVal asyncResult As System.IAsyncResult) As ProductInfo
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),ProductInfo)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:PI/DevCentral/SoapService", RequestNamespace:="urn:PI/DevCentral/SoapService", ResponseNamespace:="urn:PI/DevCentral/SoapService")>  _
        Public Function ArtistSearchRequest(<System.Xml.Serialization.SoapElementAttribute("ArtistSearchRequest")> ByVal ArtistSearchRequest1 As ArtistRequest) As <System.Xml.Serialization.SoapElementAttribute("return")> ProductInfo
            Dim results() As Object = Me.Invoke("ArtistSearchRequest", New Object() {ArtistSearchRequest1})
            Return CType(results(0),ProductInfo)
        End Function
        
        '<remarks/>
        Public Function BeginArtistSearchRequest(ByVal ArtistSearchRequest1 As ArtistRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ArtistSearchRequest", New Object() {ArtistSearchRequest1}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndArtistSearchRequest(ByVal asyncResult As System.IAsyncResult) As ProductInfo
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),ProductInfo)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:PI/DevCentral/SoapService", RequestNamespace:="urn:PI/DevCentral/SoapService", ResponseNamespace:="urn:PI/DevCentral/SoapService")>  _
        Public Function ActorSearchRequest(<System.Xml.Serialization.SoapElementAttribute("ActorSearchRequest")> ByVal ActorSearchRequest1 As ActorRequest) As <System.Xml.Serialization.SoapElementAttribute("return")> ProductInfo
            Dim results() As Object = Me.Invoke("ActorSearchRequest", New Object() {ActorSearchRequest1})
            Return CType(results(0),ProductInfo)
        End Function
        
        '<remarks/>
        Public Function BeginActorSearchRequest(ByVal ActorSearchRequest1 As ActorRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ActorSearchRequest", New Object() {ActorSearchRequest1}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndActorSearchRequest(ByVal asyncResult As System.IAsyncResult) As ProductInfo
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),ProductInfo)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:PI/DevCentral/SoapService", RequestNamespace:="urn:PI/DevCentral/SoapService", ResponseNamespace:="urn:PI/DevCentral/SoapService")>  _
        Public Function ManufacturerSearchRequest(<System.Xml.Serialization.SoapElementAttribute("ManufacturerSearchRequest")> ByVal ManufacturerSearchRequest1 As ManufacturerRequest) As <System.Xml.Serialization.SoapElementAttribute("return")> ProductInfo
            Dim results() As Object = Me.Invoke("ManufacturerSearchRequest", New Object() {ManufacturerSearchRequest1})
            Return CType(results(0),ProductInfo)
        End Function
        
        '<remarks/>
        Public Function BeginManufacturerSearchRequest(ByVal ManufacturerSearchRequest1 As ManufacturerRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ManufacturerSearchRequest", New Object() {ManufacturerSearchRequest1}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndManufacturerSearchRequest(ByVal asyncResult As System.IAsyncResult) As ProductInfo
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),ProductInfo)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:PI/DevCentral/SoapService", RequestNamespace:="urn:PI/DevCentral/SoapService", ResponseNamespace:="urn:PI/DevCentral/SoapService")>  _
        Public Function DirectorSearchRequest(<System.Xml.Serialization.SoapElementAttribute("DirectorSearchRequest")> ByVal DirectorSearchRequest1 As DirectorRequest) As <System.Xml.Serialization.SoapElementAttribute("return")> ProductInfo
            Dim results() As Object = Me.Invoke("DirectorSearchRequest", New Object() {DirectorSearchRequest1})
            Return CType(results(0),ProductInfo)
        End Function
        
        '<remarks/>
        Public Function BeginDirectorSearchRequest(ByVal DirectorSearchRequest1 As DirectorRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("DirectorSearchRequest", New Object() {DirectorSearchRequest1}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndDirectorSearchRequest(ByVal asyncResult As System.IAsyncResult) As ProductInfo
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),ProductInfo)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:PI/DevCentral/SoapService", RequestNamespace:="urn:PI/DevCentral/SoapService", ResponseNamespace:="urn:PI/DevCentral/SoapService")>  _
        Public Function ListManiaSearchRequest(<System.Xml.Serialization.SoapElementAttribute("ListManiaSearchRequest")> ByVal ListManiaSearchRequest1 As ListManiaRequest) As <System.Xml.Serialization.SoapElementAttribute("return")> ProductInfo
            Dim results() As Object = Me.Invoke("ListManiaSearchRequest", New Object() {ListManiaSearchRequest1})
            Return CType(results(0),ProductInfo)
        End Function
        
        '<remarks/>
        Public Function BeginListManiaSearchRequest(ByVal ListManiaSearchRequest1 As ListManiaRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ListManiaSearchRequest", New Object() {ListManiaSearchRequest1}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndListManiaSearchRequest(ByVal asyncResult As System.IAsyncResult) As ProductInfo
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),ProductInfo)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:PI/DevCentral/SoapService", RequestNamespace:="urn:PI/DevCentral/SoapService", ResponseNamespace:="urn:PI/DevCentral/SoapService")>  _
        Public Function WishlistSearchRequest(<System.Xml.Serialization.SoapElementAttribute("WishlistSearchRequest")> ByVal WishlistSearchRequest1 As WishlistRequest) As <System.Xml.Serialization.SoapElementAttribute("return")> ProductInfo
            Dim results() As Object = Me.Invoke("WishlistSearchRequest", New Object() {WishlistSearchRequest1})
            Return CType(results(0),ProductInfo)
        End Function
        
        '<remarks/>
        Public Function BeginWishlistSearchRequest(ByVal WishlistSearchRequest1 As WishlistRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("WishlistSearchRequest", New Object() {WishlistSearchRequest1}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndWishlistSearchRequest(ByVal asyncResult As System.IAsyncResult) As ProductInfo
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),ProductInfo)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:PI/DevCentral/SoapService", RequestNamespace:="urn:PI/DevCentral/SoapService", ResponseNamespace:="urn:PI/DevCentral/SoapService")>  _
        Public Function ExchangeSearchRequest(<System.Xml.Serialization.SoapElementAttribute("ExchangeSearchRequest")> ByVal ExchangeSearchRequest1 As ExchangeRequest) As <System.Xml.Serialization.SoapElementAttribute("return")> ListingProductDetails
            Dim results() As Object = Me.Invoke("ExchangeSearchRequest", New Object() {ExchangeSearchRequest1})
            Return CType(results(0),ListingProductDetails)
        End Function
        
        '<remarks/>
        Public Function BeginExchangeSearchRequest(ByVal ExchangeSearchRequest1 As ExchangeRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ExchangeSearchRequest", New Object() {ExchangeSearchRequest1}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndExchangeSearchRequest(ByVal asyncResult As System.IAsyncResult) As ListingProductDetails
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),ListingProductDetails)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:PI/DevCentral/SoapService", RequestNamespace:="urn:PI/DevCentral/SoapService", ResponseNamespace:="urn:PI/DevCentral/SoapService")>  _
        Public Function SellerProfileSearchRequest(<System.Xml.Serialization.SoapElementAttribute("SellerProfileSearchRequest")> ByVal SellerProfileSearchRequest1 As SellerProfileRequest) As <System.Xml.Serialization.SoapElementAttribute("return")> SellerProfile
            Dim results() As Object = Me.Invoke("SellerProfileSearchRequest", New Object() {SellerProfileSearchRequest1})
            Return CType(results(0),SellerProfile)
        End Function
        
        '<remarks/>
        Public Function BeginSellerProfileSearchRequest(ByVal SellerProfileSearchRequest1 As SellerProfileRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("SellerProfileSearchRequest", New Object() {SellerProfileSearchRequest1}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndSellerProfileSearchRequest(ByVal asyncResult As System.IAsyncResult) As SellerProfile
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),SellerProfile)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:PI/DevCentral/SoapService", RequestNamespace:="urn:PI/DevCentral/SoapService", ResponseNamespace:="urn:PI/DevCentral/SoapService")>  _
        Public Function SellerSearchRequest(<System.Xml.Serialization.SoapElementAttribute("SellerSearchRequest")> ByVal SellerSearchRequest1 As SellerRequest) As <System.Xml.Serialization.SoapElementAttribute("return")> SellerSearch
            Dim results() As Object = Me.Invoke("SellerSearchRequest", New Object() {SellerSearchRequest1})
            Return CType(results(0),SellerSearch)
        End Function
        
        '<remarks/>
        Public Function BeginSellerSearchRequest(ByVal SellerSearchRequest1 As SellerRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("SellerSearchRequest", New Object() {SellerSearchRequest1}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndSellerSearchRequest(ByVal asyncResult As System.IAsyncResult) As SellerSearch
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),SellerSearch)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:PI/DevCentral/SoapService", RequestNamespace:="urn:PI/DevCentral/SoapService", ResponseNamespace:="urn:PI/DevCentral/SoapService")>  _
        Public Function SimilaritySearchRequest(<System.Xml.Serialization.SoapElementAttribute("SimilaritySearchRequest")> ByVal SimilaritySearchRequest1 As SimilarityRequest) As <System.Xml.Serialization.SoapElementAttribute("return")> ProductInfo
            Dim results() As Object = Me.Invoke("SimilaritySearchRequest", New Object() {SimilaritySearchRequest1})
            Return CType(results(0),ProductInfo)
        End Function
        
        '<remarks/>
        Public Function BeginSimilaritySearchRequest(ByVal SimilaritySearchRequest1 As SimilarityRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("SimilaritySearchRequest", New Object() {SimilaritySearchRequest1}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndSimilaritySearchRequest(ByVal asyncResult As System.IAsyncResult) As ProductInfo
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),ProductInfo)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:PI/DevCentral/SoapService", RequestNamespace:="urn:PI/DevCentral/SoapService", ResponseNamespace:="urn:PI/DevCentral/SoapService")>  _
        Public Function GetShoppingCartRequest(<System.Xml.Serialization.SoapElementAttribute("GetShoppingCartRequest")> ByVal GetShoppingCartRequest1 As GetShoppingCartRequest) As <System.Xml.Serialization.SoapElementAttribute("ShoppingCart")> ShoppingCart
            Dim results() As Object = Me.Invoke("GetShoppingCartRequest", New Object() {GetShoppingCartRequest1})
            Return CType(results(0),ShoppingCart)
        End Function
        
        '<remarks/>
        Public Function BeginGetShoppingCartRequest(ByVal GetShoppingCartRequest1 As GetShoppingCartRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetShoppingCartRequest", New Object() {GetShoppingCartRequest1}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGetShoppingCartRequest(ByVal asyncResult As System.IAsyncResult) As ShoppingCart
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),ShoppingCart)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:PI/DevCentral/SoapService", RequestNamespace:="urn:PI/DevCentral/SoapService", ResponseNamespace:="urn:PI/DevCentral/SoapService")>  _
        Public Function ClearShoppingCartRequest(<System.Xml.Serialization.SoapElementAttribute("ClearShoppingCartRequest")> ByVal ClearShoppingCartRequest1 As ClearShoppingCartRequest) As <System.Xml.Serialization.SoapElementAttribute("ShoppingCart")> ShoppingCart
            Dim results() As Object = Me.Invoke("ClearShoppingCartRequest", New Object() {ClearShoppingCartRequest1})
            Return CType(results(0),ShoppingCart)
        End Function
        
        '<remarks/>
        Public Function BeginClearShoppingCartRequest(ByVal ClearShoppingCartRequest1 As ClearShoppingCartRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ClearShoppingCartRequest", New Object() {ClearShoppingCartRequest1}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndClearShoppingCartRequest(ByVal asyncResult As System.IAsyncResult) As ShoppingCart
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),ShoppingCart)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:PI/DevCentral/SoapService", RequestNamespace:="urn:PI/DevCentral/SoapService", ResponseNamespace:="urn:PI/DevCentral/SoapService")>  _
        Public Function AddShoppingCartItemsRequest(<System.Xml.Serialization.SoapElementAttribute("AddShoppingCartItemsRequest")> ByVal AddShoppingCartItemsRequest1 As AddShoppingCartItemsRequest) As <System.Xml.Serialization.SoapElementAttribute("ShoppingCart")> ShoppingCart
            Dim results() As Object = Me.Invoke("AddShoppingCartItemsRequest", New Object() {AddShoppingCartItemsRequest1})
            Return CType(results(0),ShoppingCart)
        End Function
        
        '<remarks/>
        Public Function BeginAddShoppingCartItemsRequest(ByVal AddShoppingCartItemsRequest1 As AddShoppingCartItemsRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("AddShoppingCartItemsRequest", New Object() {AddShoppingCartItemsRequest1}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndAddShoppingCartItemsRequest(ByVal asyncResult As System.IAsyncResult) As ShoppingCart
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),ShoppingCart)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:PI/DevCentral/SoapService", RequestNamespace:="urn:PI/DevCentral/SoapService", ResponseNamespace:="urn:PI/DevCentral/SoapService")>  _
        Public Function RemoveShoppingCartItemsRequest(<System.Xml.Serialization.SoapElementAttribute("RemoveShoppingCartItemsRequest")> ByVal RemoveShoppingCartItemsRequest1 As RemoveShoppingCartItemsRequest) As <System.Xml.Serialization.SoapElementAttribute("ShoppingCart")> ShoppingCart
            Dim results() As Object = Me.Invoke("RemoveShoppingCartItemsRequest", New Object() {RemoveShoppingCartItemsRequest1})
            Return CType(results(0),ShoppingCart)
        End Function
        
        '<remarks/>
        Public Function BeginRemoveShoppingCartItemsRequest(ByVal RemoveShoppingCartItemsRequest1 As RemoveShoppingCartItemsRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("RemoveShoppingCartItemsRequest", New Object() {RemoveShoppingCartItemsRequest1}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndRemoveShoppingCartItemsRequest(ByVal asyncResult As System.IAsyncResult) As ShoppingCart
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),ShoppingCart)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:PI/DevCentral/SoapService", RequestNamespace:="urn:PI/DevCentral/SoapService", ResponseNamespace:="urn:PI/DevCentral/SoapService")>  _
        Public Function ModifyShoppingCartItemsRequest(<System.Xml.Serialization.SoapElementAttribute("ModifyShoppingCartItemsRequest")> ByVal ModifyShoppingCartItemsRequest1 As ModifyShoppingCartItemsRequest) As <System.Xml.Serialization.SoapElementAttribute("ShoppingCart")> ShoppingCart
            Dim results() As Object = Me.Invoke("ModifyShoppingCartItemsRequest", New Object() {ModifyShoppingCartItemsRequest1})
            Return CType(results(0),ShoppingCart)
        End Function
        
        '<remarks/>
        Public Function BeginModifyShoppingCartItemsRequest(ByVal ModifyShoppingCartItemsRequest1 As ModifyShoppingCartItemsRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ModifyShoppingCartItemsRequest", New Object() {ModifyShoppingCartItemsRequest1}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndModifyShoppingCartItemsRequest(ByVal asyncResult As System.IAsyncResult) As ShoppingCart
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),ShoppingCart)
        End Function
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.SoapTypeAttribute("KeywordRequest", "urn:PI/DevCentral/SoapService")>  _
    Public Class KeywordRequest
        
        '<remarks/>
        Public keyword As String
        
        '<remarks/>
        Public page As String
        
        '<remarks/>
        Public mode As String
        
        '<remarks/>
        Public tag As String
        
        '<remarks/>
        Public type As String
        
        '<remarks/>
        Public devtag As String
        
        '<remarks/>
        Public sort As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.SoapTypeAttribute("ItemQuantity", "urn:PI/DevCentral/SoapService")>  _
    Public Class ItemQuantity
        
        '<remarks/>
        Public ItemId As String
        
        '<remarks/>
        Public Quantity As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.SoapTypeAttribute("ModifyShoppingCartItemsRequest", "urn:PI/DevCentral/SoapService")>  _
    Public Class ModifyShoppingCartItemsRequest
        
        '<remarks/>
        Public tag As String
        
        '<remarks/>
        Public devtag As String
        
        '<remarks/>
        Public CartId As String
        
        '<remarks/>
        Public HMAC As String
        
        '<remarks/>
        Public Items() As ItemQuantity
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.SoapTypeAttribute("RemoveShoppingCartItemsRequest", "urn:PI/DevCentral/SoapService")>  _
    Public Class RemoveShoppingCartItemsRequest
        
        '<remarks/>
        Public tag As String
        
        '<remarks/>
        Public devtag As String
        
        '<remarks/>
        Public CartId As String
        
        '<remarks/>
        Public HMAC As String
        
        '<remarks/>
        Public Items() As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.SoapTypeAttribute("AddItem", "urn:PI/DevCentral/SoapService")>  _
    Public Class AddItem
        
        '<remarks/>
        Public Asin As String
        
        '<remarks/>
        Public ExchangeId As String
        
        '<remarks/>
        Public Quantity As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.SoapTypeAttribute("AddShoppingCartItemsRequest", "urn:PI/DevCentral/SoapService")>  _
    Public Class AddShoppingCartItemsRequest
        
        '<remarks/>
        Public tag As String
        
        '<remarks/>
        Public devtag As String
        
        '<remarks/>
        Public CartId As String
        
        '<remarks/>
        Public HMAC As String
        
        '<remarks/>
        Public Items() As AddItem
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.SoapTypeAttribute("ClearShoppingCartRequest", "urn:PI/DevCentral/SoapService")>  _
    Public Class ClearShoppingCartRequest
        
        '<remarks/>
        Public tag As String
        
        '<remarks/>
        Public devtag As String
        
        '<remarks/>
        Public CartId As String
        
        '<remarks/>
        Public HMAC As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.SoapTypeAttribute("Item", "urn:PI/DevCentral/SoapService")>  _
    Public Class Item
        
        '<remarks/>
        Public ItemId As String
        
        '<remarks/>
        Public ProductName As String
        
        '<remarks/>
        Public Catalog As String
        
        '<remarks/>
        Public Asin As String
        
        '<remarks/>
        Public ExchangeId As String
        
        '<remarks/>
        Public Quantity As String
        
        '<remarks/>
        Public ListPrice As String
        
        '<remarks/>
        Public OurPrice As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.SoapTypeAttribute("ShoppingCart", "urn:PI/DevCentral/SoapService")>  _
    Public Class ShoppingCart
        
        '<remarks/>
        Public CartId As String
        
        '<remarks/>
        Public HMAC As String
        
        '<remarks/>
        Public PurchaseUrl As String
        
        '<remarks/>
        Public Items() As Item
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.SoapTypeAttribute("GetShoppingCartRequest", "urn:PI/DevCentral/SoapService")>  _
    Public Class GetShoppingCartRequest
        
        '<remarks/>
        Public tag As String
        
        '<remarks/>
        Public devtag As String
        
        '<remarks/>
        Public HMAC As String
        
        '<remarks/>
        Public CartId As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.SoapTypeAttribute("SimilarityRequest", "urn:PI/DevCentral/SoapService")>  _
    Public Class SimilarityRequest
        
        '<remarks/>
        Public asin As String
        
        '<remarks/>
        Public tag As String
        
        '<remarks/>
        Public type As String
        
        '<remarks/>
        Public devtag As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.SoapTypeAttribute("ListingProductInfo", "urn:PI/DevCentral/SoapService")>  _
    Public Class ListingProductInfo
        
        '<remarks/>
        Public ListingProductDetails() As ListingProductDetails
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.SoapTypeAttribute("ListingProductDetails", "urn:PI/DevCentral/SoapService")>  _
    Public Class ListingProductDetails
        
        '<remarks/>
        Public ExchangeId As String
        
        '<remarks/>
        Public ListingId As String
        
        '<remarks/>
        Public ExchangeTitle As String
        
        '<remarks/>
        Public ExchangePrice As String
        
        '<remarks/>
        Public ExchangeAsin As String
        
        '<remarks/>
        Public ExchangeEndDate As String
        
        '<remarks/>
        Public ExchangeTinyImage As String
        
        '<remarks/>
        Public ExchangeSellerId As String
        
        '<remarks/>
        Public ExchangeSellerNickname As String
        
        '<remarks/>
        Public ExchangeStartDate As String
        
        '<remarks/>
        Public ExchangeStatus As String
        
        '<remarks/>
        Public ExchangeQuantity As String
        
        '<remarks/>
        Public ExchangeQuantityAllocated As String
        
        '<remarks/>
        Public ExchangeFeaturedCategory As String
        
        '<remarks/>
        Public ExchangeCondition As String
        
        '<remarks/>
        Public ExchangeConditionType As String
        
        '<remarks/>
        Public ExchangeAvailability As String
        
        '<remarks/>
        Public ExchangeOfferingType As String
        
        '<remarks/>
        Public ExchangeSellerState As String
        
        '<remarks/>
        Public ExchangeSellerCountry As String
        
        '<remarks/>
        Public ExchangeSellerRating As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.SoapTypeAttribute("SellerSearchDetails", "urn:PI/DevCentral/SoapService")>  _
    Public Class SellerSearchDetails
        
        '<remarks/>
        Public SellerNickname As String
        
        '<remarks/>
        Public StoreId As String
        
        '<remarks/>
        Public StoreName As String
        
        '<remarks/>
        Public NumberOfOpenListings As String
        
        '<remarks/>
        Public ListingProductInfo As ListingProductInfo
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.SoapTypeAttribute("SellerSearch", "urn:PI/DevCentral/SoapService")>  _
    Public Class SellerSearch
        
        '<remarks/>
        Public SellerSearchDetails() As SellerSearchDetails
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.SoapTypeAttribute("SellerRequest", "urn:PI/DevCentral/SoapService")>  _
    Public Class SellerRequest
        
        '<remarks/>
        Public seller_id As String
        
        '<remarks/>
        Public tag As String
        
        '<remarks/>
        Public type As String
        
        '<remarks/>
        Public devtag As String
        
        '<remarks/>
        Public offerstatus As String
        
        '<remarks/>
        Public page As String
        
        '<remarks/>
        Public seller_browse_id As String
        
        '<remarks/>
        Public keyword As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.SoapTypeAttribute("Feedback", "urn:PI/DevCentral/SoapService")>  _
    Public Class Feedback
        
        '<remarks/>
        Public FeedbackRating As String
        
        '<remarks/>
        Public FeedbackComments As String
        
        '<remarks/>
        Public FeedbackDate As String
        
        '<remarks/>
        Public FeedbackRater As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.SoapTypeAttribute("SellerFeedback", "urn:PI/DevCentral/SoapService")>  _
    Public Class SellerFeedback
        
        '<remarks/>
        Public Feedback() As Feedback
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.SoapTypeAttribute("SellerProfileDetails", "urn:PI/DevCentral/SoapService")>  _
    Public Class SellerProfileDetails
        
        '<remarks/>
        Public SellerNickname As String
        
        '<remarks/>
        Public OverallFeedbackRating As String
        
        '<remarks/>
        Public NumberOfFeedback As String
        
        '<remarks/>
        Public NumberOfCanceledBids As String
        
        '<remarks/>
        Public NumberOfCanceledAuctions As String
        
        '<remarks/>
        Public StoreId As String
        
        '<remarks/>
        Public StoreName As String
        
        '<remarks/>
        Public SellerFeedback As SellerFeedback
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.SoapTypeAttribute("SellerProfile", "urn:PI/DevCentral/SoapService")>  _
    Public Class SellerProfile
        
        '<remarks/>
        Public SellerProfileDetails() As SellerProfileDetails
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.SoapTypeAttribute("SellerProfileRequest", "urn:PI/DevCentral/SoapService")>  _
    Public Class SellerProfileRequest
        
        '<remarks/>
        Public seller_id As String
        
        '<remarks/>
        Public tag As String
        
        '<remarks/>
        Public type As String
        
        '<remarks/>
        Public devtag As String
        
        '<remarks/>
        Public page As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.SoapTypeAttribute("ExchangeRequest", "urn:PI/DevCentral/SoapService")>  _
    Public Class ExchangeRequest
        
        '<remarks/>
        Public exchange_id As String
        
        '<remarks/>
        Public tag As String
        
        '<remarks/>
        Public type As String
        
        '<remarks/>
        Public devtag As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.SoapTypeAttribute("WishlistRequest", "urn:PI/DevCentral/SoapService")>  _
    Public Class WishlistRequest
        
        '<remarks/>
        Public wishlist_id As String
        
        '<remarks/>
        Public page As String
        
        '<remarks/>
        Public tag As String
        
        '<remarks/>
        Public type As String
        
        '<remarks/>
        Public devtag As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.SoapTypeAttribute("ListManiaRequest", "urn:PI/DevCentral/SoapService")>  _
    Public Class ListManiaRequest
        
        '<remarks/>
        Public lm_id As String
        
        '<remarks/>
        Public page As String
        
        '<remarks/>
        Public tag As String
        
        '<remarks/>
        Public type As String
        
        '<remarks/>
        Public devtag As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.SoapTypeAttribute("DirectorRequest", "urn:PI/DevCentral/SoapService")>  _
    Public Class DirectorRequest
        
        '<remarks/>
        Public director As String
        
        '<remarks/>
        Public page As String
        
        '<remarks/>
        Public mode As String
        
        '<remarks/>
        Public tag As String
        
        '<remarks/>
        Public type As String
        
        '<remarks/>
        Public devtag As String
        
        '<remarks/>
        Public sort As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.SoapTypeAttribute("ManufacturerRequest", "urn:PI/DevCentral/SoapService")>  _
    Public Class ManufacturerRequest
        
        '<remarks/>
        Public manufacturer As String
        
        '<remarks/>
        Public page As String
        
        '<remarks/>
        Public mode As String
        
        '<remarks/>
        Public tag As String
        
        '<remarks/>
        Public type As String
        
        '<remarks/>
        Public devtag As String
        
        '<remarks/>
        Public sort As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.SoapTypeAttribute("ActorRequest", "urn:PI/DevCentral/SoapService")>  _
    Public Class ActorRequest
        
        '<remarks/>
        Public actor As String
        
        '<remarks/>
        Public page As String
        
        '<remarks/>
        Public mode As String
        
        '<remarks/>
        Public tag As String
        
        '<remarks/>
        Public type As String
        
        '<remarks/>
        Public devtag As String
        
        '<remarks/>
        Public sort As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.SoapTypeAttribute("ArtistRequest", "urn:PI/DevCentral/SoapService")>  _
    Public Class ArtistRequest
        
        '<remarks/>
        Public artist As String
        
        '<remarks/>
        Public page As String
        
        '<remarks/>
        Public mode As String
        
        '<remarks/>
        Public tag As String
        
        '<remarks/>
        Public type As String
        
        '<remarks/>
        Public devtag As String
        
        '<remarks/>
        Public sort As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.SoapTypeAttribute("AuthorRequest", "urn:PI/DevCentral/SoapService")>  _
    Public Class AuthorRequest
        
        '<remarks/>
        Public author As String
        
        '<remarks/>
        Public page As String
        
        '<remarks/>
        Public mode As String
        
        '<remarks/>
        Public tag As String
        
        '<remarks/>
        Public type As String
        
        '<remarks/>
        Public devtag As String
        
        '<remarks/>
        Public sort As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.SoapTypeAttribute("UpcRequest", "urn:PI/DevCentral/SoapService")>  _
    Public Class UpcRequest
        
        '<remarks/>
        Public upc As String
        
        '<remarks/>
        Public mode As String
        
        '<remarks/>
        Public tag As String
        
        '<remarks/>
        Public type As String
        
        '<remarks/>
        Public devtag As String
        
        '<remarks/>
        Public sort As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.SoapTypeAttribute("AsinRequest", "urn:PI/DevCentral/SoapService")>  _
    Public Class AsinRequest
        
        '<remarks/>
        Public asin As String
        
        '<remarks/>
        Public tag As String
        
        '<remarks/>
        Public type As String
        
        '<remarks/>
        Public devtag As String
        
        '<remarks/>
        Public offer As String
        
        '<remarks/>
        Public offerpage As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.SoapTypeAttribute("BrowseNodeRequest", "urn:PI/DevCentral/SoapService")>  _
    Public Class BrowseNodeRequest
        
        '<remarks/>
        Public browse_node As String
        
        '<remarks/>
        Public page As String
        
        '<remarks/>
        Public mode As String
        
        '<remarks/>
        Public tag As String
        
        '<remarks/>
        Public type As String
        
        '<remarks/>
        Public devtag As String
        
        '<remarks/>
        Public sort As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.SoapTypeAttribute("PowerRequest", "urn:PI/DevCentral/SoapService")>  _
    Public Class PowerRequest
        
        '<remarks/>
        Public power As String
        
        '<remarks/>
        Public mode As String
        
        '<remarks/>
        Public tag As String
        
        '<remarks/>
        Public type As String
        
        '<remarks/>
        Public devtag As String
        
        '<remarks/>
        Public sort As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.SoapTypeAttribute("CustomerReview", "urn:PI/DevCentral/SoapService")>  _
    Public Class CustomerReview
        
        '<remarks/>
        Public Rating As String
        
        '<remarks/>
        Public Summary As String
        
        '<remarks/>
        Public Comment As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.SoapTypeAttribute("Reviews", "urn:PI/DevCentral/SoapService")>  _
    Public Class Reviews
        
        '<remarks/>
        Public AvgCustomerRating As String
        
        '<remarks/>
        Public CustomerReviews() As CustomerReview
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.SoapTypeAttribute("Track", "urn:PI/DevCentral/SoapService")>  _
    Public Class Track
        
        '<remarks/>
        Public TrackName As String
        
        '<remarks/>
        Public ByArtist As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.SoapTypeAttribute("BrowseNode", "urn:PI/DevCentral/SoapService")>  _
    Public Class BrowseNode
        
        '<remarks/>
        Public BrowseId As String
        
        '<remarks/>
        Public BrowseName As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.SoapTypeAttribute("ThirdPartyProductDetails", "urn:PI/DevCentral/SoapService")>  _
    Public Class ThirdPartyProductDetails
        
        '<remarks/>
        Public OfferingType As String
        
        '<remarks/>
        Public SellerId As String
        
        '<remarks/>
        Public SellerNickname As String
        
        '<remarks/>
        Public ExchangeId As String
        
        '<remarks/>
        Public OfferingPrice As String
        
        '<remarks/>
        Public Condition As String
        
        '<remarks/>
        Public ConditionType As String
        
        '<remarks/>
        Public ExchangeAvailability As String
        
        '<remarks/>
        Public SellerCountry As String
        
        '<remarks/>
        Public SellerState As String
        
        '<remarks/>
        Public ShipComments As String
        
        '<remarks/>
        Public SellerRating As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.SoapTypeAttribute("ThirdPartyProductInfo", "urn:PI/DevCentral/SoapService")>  _
    Public Class ThirdPartyProductInfo
        
        '<remarks/>
        Public ThirdPartyProductDetails() As ThirdPartyProductDetails
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.SoapTypeAttribute("KeyPhrase", "urn:PI/DevCentral/SoapService")>  _
    Public Class KeyPhrase
        
        '<remarks/>
        <System.Xml.Serialization.SoapElementAttribute("KeyPhrase")>  _
        Public KeyPhrase1 As String
        
        '<remarks/>
        Public Type As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.SoapTypeAttribute("Details", "urn:PI/DevCentral/SoapService")>  _
    Public Class Details
        
        '<remarks/>
        Public Url As String
        
        '<remarks/>
        Public Asin As String
        
        '<remarks/>
        Public ProductName As String
        
        '<remarks/>
        Public Catalog As String
        
        '<remarks/>
        Public KeyPhrases() As KeyPhrase
        
        '<remarks/>
        Public Artists() As String
        
        '<remarks/>
        Public Authors() As String
        
        '<remarks/>
        Public Mpn As String
        
        '<remarks/>
        Public Starring() As String
        
        '<remarks/>
        Public Directors() As String
        
        '<remarks/>
        Public TheatricalReleaseDate As String
        
        '<remarks/>
        Public ReleaseDate As String
        
        '<remarks/>
        Public Manufacturer As String
        
        '<remarks/>
        Public Distributor As String
        
        '<remarks/>
        Public ImageUrlSmall As String
        
        '<remarks/>
        Public ImageUrlMedium As String
        
        '<remarks/>
        Public ImageUrlLarge As String
        
        '<remarks/>
        Public ListPrice As String
        
        '<remarks/>
        Public OurPrice As String
        
        '<remarks/>
        Public UsedPrice As String
        
        '<remarks/>
        Public RefurbishedPrice As String
        
        '<remarks/>
        Public CollectiblePrice As String
        
        '<remarks/>
        Public ThirdPartyNewPrice As String
        
        '<remarks/>
        Public NumberOfOfferings As String
        
        '<remarks/>
        Public ThirdPartyNewCount As String
        
        '<remarks/>
        Public UsedCount As String
        
        '<remarks/>
        Public CollectibleCount As String
        
        '<remarks/>
        Public RefurbishedCount As String
        
        '<remarks/>
        Public ThirdPartyProductInfo As ThirdPartyProductInfo
        
        '<remarks/>
        Public SalesRank As String
        
        '<remarks/>
        Public BrowseList() As BrowseNode
        
        '<remarks/>
        Public Media As String
        
        '<remarks/>
        Public ReadingLevel As String
        
        '<remarks/>
        Public Publisher As String
        
        '<remarks/>
        Public NumMedia As String
        
        '<remarks/>
        Public Isbn As String
        
        '<remarks/>
        Public Features() As String
        
        '<remarks/>
        Public MpaaRating As String
        
        '<remarks/>
        Public EsrbRating As String
        
        '<remarks/>
        Public AgeGroup As String
        
        '<remarks/>
        Public Availability As String
        
        '<remarks/>
        Public Upc As String
        
        '<remarks/>
        Public Tracks() As Track
        
        '<remarks/>
        Public Accessories() As String
        
        '<remarks/>
        Public Platforms() As String
        
        '<remarks/>
        Public Encoding As String
        
        '<remarks/>
        Public Reviews As Reviews
        
        '<remarks/>
        Public SimilarProducts() As String
        
        '<remarks/>
        Public Lists() As String
        
        '<remarks/>
        Public Status As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.SoapTypeAttribute("ProductInfo", "urn:PI/DevCentral/SoapService")>  _
    Public Class ProductInfo
        
        '<remarks/>
        Public TotalResults As String
        
        '<remarks/>
        Public ListName As String
        
        '<remarks/>
        Public Details() As Details
    End Class
End Namespace
