'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.0.3705.288
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.0.3705.288.
'
Namespace com.google.api
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="GoogleSearchBinding", [Namespace]:="urn:GoogleSearch"),  _
     System.Xml.Serialization.SoapIncludeAttribute(GetType(ResultElement))>  _
    Public Class GoogleSearchService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://api.google.com/search/beta2"
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:GoogleSearchAction", RequestNamespace:="urn:GoogleSearch", ResponseNamespace:="urn:GoogleSearch")>  _
        Public Function doGetCachedPage(ByVal key As String, ByVal url As String) As <System.Xml.Serialization.SoapElementAttribute("return", DataType:="base64Binary")> Byte()
            Dim results() As Object = Me.Invoke("doGetCachedPage", New Object() {key, url})
            Return CType(results(0),Byte())
        End Function
        
        '<remarks/>
        Public Function BegindoGetCachedPage(ByVal key As String, ByVal url As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("doGetCachedPage", New Object() {key, url}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EnddoGetCachedPage(ByVal asyncResult As System.IAsyncResult) As Byte()
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Byte())
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:GoogleSearchAction", RequestNamespace:="urn:GoogleSearch", ResponseNamespace:="urn:GoogleSearch")>  _
        Public Function doSpellingSuggestion(ByVal key As String, ByVal phrase As String) As <System.Xml.Serialization.SoapElementAttribute("return")> String
            Dim results() As Object = Me.Invoke("doSpellingSuggestion", New Object() {key, phrase})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BegindoSpellingSuggestion(ByVal key As String, ByVal phrase As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("doSpellingSuggestion", New Object() {key, phrase}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EnddoSpellingSuggestion(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:GoogleSearchAction", RequestNamespace:="urn:GoogleSearch", ResponseNamespace:="urn:GoogleSearch")>  _
        Public Function doGoogleSearch(ByVal key As String, ByVal q As String, ByVal start As Integer, ByVal maxResults As Integer, ByVal filter As Boolean, ByVal restrict As String, ByVal safeSearch As Boolean, ByVal lr As String, ByVal ie As String, ByVal oe As String) As <System.Xml.Serialization.SoapElementAttribute("return")> GoogleSearchResult
            Dim results() As Object = Me.Invoke("doGoogleSearch", New Object() {key, q, start, maxResults, filter, restrict, safeSearch, lr, ie, oe})
            Return CType(results(0),GoogleSearchResult)
        End Function
        
        '<remarks/>
        Public Function BegindoGoogleSearch(ByVal key As String, ByVal q As String, ByVal start As Integer, ByVal maxResults As Integer, ByVal filter As Boolean, ByVal restrict As String, ByVal safeSearch As Boolean, ByVal lr As String, ByVal ie As String, ByVal oe As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("doGoogleSearch", New Object() {key, q, start, maxResults, filter, restrict, safeSearch, lr, ie, oe}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EnddoGoogleSearch(ByVal asyncResult As System.IAsyncResult) As GoogleSearchResult
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),GoogleSearchResult)
        End Function
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.SoapTypeAttribute("GoogleSearchResult", "urn:GoogleSearch")>  _
    Public Class GoogleSearchResult
        
        '<remarks/>
        Public documentFiltering As Boolean
        
        '<remarks/>
        Public searchComments As String
        
        '<remarks/>
        Public estimatedTotalResultsCount As Integer
        
        '<remarks/>
        Public estimateIsExact As Boolean
        
        '<remarks/>
        Public resultElements() As ResultElement
        
        '<remarks/>
        Public searchQuery As String
        
        '<remarks/>
        Public startIndex As Integer
        
        '<remarks/>
        Public endIndex As Integer
        
        '<remarks/>
        Public searchTips As String
        
        '<remarks/>
        Public directoryCategories() As DirectoryCategory
        
        '<remarks/>
        Public searchTime As Double
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.SoapTypeAttribute("ResultElement", "urn:GoogleSearch")>  _
    Public Class ResultElement
        
        '<remarks/>
        Public summary As String
        
        '<remarks/>
        Public URL As String
        
        '<remarks/>
        Public snippet As String
        
        '<remarks/>
        Public title As String
        
        '<remarks/>
        Public cachedSize As String
        
        '<remarks/>
        Public relatedInformationPresent As Boolean
        
        '<remarks/>
        Public hostName As String
        
        '<remarks/>
        Public directoryCategory As DirectoryCategory
        
        '<remarks/>
        Public directoryTitle As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.SoapTypeAttribute("DirectoryCategory", "urn:GoogleSearch")>  _
    Public Class DirectoryCategory
        
        '<remarks/>
        Public fullViewableName As String
        
        '<remarks/>
        Public specialEncoding As String
    End Class
End Namespace
