Public Class Form1
    Inherits System.Windows.Forms.Form

#Region " Windows Form Designer generated code "

    Public Sub New()
        MyBase.New()

        'This call is required by the Windows Form Designer.
        InitializeComponent()

        'Add any initialization after the InitializeComponent() call

    End Sub

    'Form overrides dispose to clean up the component list.
    Protected Overloads Overrides Sub Dispose(ByVal disposing As Boolean)
        If disposing Then
            If Not (components Is Nothing) Then
                components.Dispose()
            End If
        End If
        MyBase.Dispose(disposing)
    End Sub

    'Required by the Windows Form Designer
    Private components As System.ComponentModel.IContainer

    'NOTE: The following procedure is required by the Windows Form Designer
    'It can be modified using the Windows Form Designer.  
    'Do not modify it using the code editor.
    Friend WithEvents Label1 As System.Windows.Forms.Label
    Friend WithEvents Label2 As System.Windows.Forms.Label
    Friend WithEvents Button1 As System.Windows.Forms.Button
    <System.Diagnostics.DebuggerStepThrough()> Private Sub InitializeComponent()
        Me.Label1 = New System.Windows.Forms.Label()
        Me.Label2 = New System.Windows.Forms.Label()
        Me.Button1 = New System.Windows.Forms.Button()
        Me.SuspendLayout()
        '
        'Label1
        '
        Me.Label1.Font = New System.Drawing.Font("Arial", 12.0!, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.Label1.Location = New System.Drawing.Point(16, 16)
        Me.Label1.Name = "Label1"
        Me.Label1.Size = New System.Drawing.Size(336, 24)
        Me.Label1.TabIndex = 0
        Me.Label1.Text = "Finding the Last Identity Number Added"
        '
        'Label2
        '
        Me.Label2.Location = New System.Drawing.Point(16, 48)
        Me.Label2.Name = "Label2"
        Me.Label2.Size = New System.Drawing.Size(376, 40)
        Me.Label2.TabIndex = 1
        Me.Label2.Text = "This example uses the SQL Server ""pubs"" database to add a row to the ""jobs"" table" & _
        " and report back with the autogenerated ID number."
        '
        'Button1
        '
        Me.Button1.Location = New System.Drawing.Point(112, 96)
        Me.Button1.Name = "Button1"
        Me.Button1.Size = New System.Drawing.Size(176, 32)
        Me.Button1.TabIndex = 2
        Me.Button1.Text = "Click here to add row"
        '
        'Form1
        '
        Me.AutoScaleBaseSize = New System.Drawing.Size(5, 13)
        Me.ClientSize = New System.Drawing.Size(400, 158)
        Me.Controls.AddRange(New System.Windows.Forms.Control() {Me.Button1, Me.Label2, Me.Label1})
        Me.Name = "Form1"
        Me.Text = "Finding the Last Identity Number Added"
        Me.ResumeLayout(False)

    End Sub

#End Region

    Private Sub Button1_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles Button1.Click
        ' Variable to hold the identity value of our record
        Dim MyIdentityValue As Integer
        ' Setup sample connection and command
        Dim objConnection As New SqlClient.SqlConnection( _
            "server=.;database=pubs;" & _
            "trusted_connection=true")
        Dim objCommand As New SqlClient.SqlCommand( _
            "INSERT INTO jobs (job_desc, min_lvl, max_lvl) " & _
            "VALUES('In-house Author', 50, 100)")
        ' Open connection and execute INSERT command
        objConnection.Open()
        objCommand.Connection = objConnection
        ' Execute and check minimum of one record affected...
        If objCommand.ExecuteNonQuery > 0 = True Then
            ' Setup separate command to retrieve identity value
            Dim objIdentifier As New _
               SqlClient.SqlCommand("Select @@Identity", objConnection)
            Try
                ' Return value of field
                MyIdentityValue = objIdentifier.ExecuteScalar
            Catch
                MyIdentityValue = 0
            End Try
        End If
        ' Close connection
        objConnection.Close()
        ' Display value
        MessageBox.Show("The autogenerated identity number was " & MyIdentityValue)
    End Sub
End Class
